---
application: datacat
repository: git@github.com:galterlibrary/rdcat.git
deployer: deploy
contact_email: piotr.hebal@northwestern.edu
development:
  server_name: rdcat.dev
test:
  server_name: rdcat.dev
staging:
  app_host: vtfsmnubicapps01.fsm.northwestern.edu
  server_name: rdcat-staging.nubic.northwestern.edu
  server_alias: rdcat-staging.nubic.northwestern.edu
  cert_file: /etc/pki/tls/certs/rdcat-staging_nubic_northwestern_edu_cert.cer
  chain_file: /etc/pki/tls/certs/rdcat-staging_nubic_northwestern_edu_interm.cer
  key_file: /etc/pki/tls/private/rdcat-staging.key
production:
  app_host: vfsmnubicapps01.fsm.northwestern.edu
  server_name: rdcat.nubic.northwestern.edu
  server_alias: rdcat.nubic.northwestern.edu
office:
  app_host: galter-2310-1.fsm.northwestern.edu
  server_name: galter-2310-1.fsm.northwestern.edu
  server_alias: galter-2310-1.fsm.northwestern.edu
  cert_file: /etc/pki/tls/certs/localhost.crt
  #chain_file: /etc/pki/tls/certs/rdcat-staging_nubic_northwestern_edu_interm.cer
  key_file: /etc/pki/tls/private/localhost.key
