default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rdcat_development

test:
  <<: *default
  database: <%= ENV['DB_TEST'] || 'rdcat_test' %>

production:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] || 'vfsmghsldb01.fsm.northwestern.edu' %>
  database: <%= ENV['DATABASE_NAME'] || 'datacat' %>
  username: <%= ENV['DATABASE_USER'] || 'datacat_user' %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

staging:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] || 'vtfsmghsldb01.fsm.northwestern.edu' %>
  database: <%= ENV['DATABASE_NAME'] || 'datacat_staging' %>
  username: <%= ENV['DATABASE_USER'] || 'datacat_staging_user' %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
