## Authorizations
# Uncomment out the merging for each environment that you'd like to include.
# You can also just copy and paste the tree (do not include the "authorizations") to each
# environment if you need something different per environment. 
authorizations: &AUTHORIZATIONS
  allow_unauthenticated_bind: false
  group_base: ou=groups,dc=northwestern,dc=edu
  ## Requires config.ldap_check_group_membership in devise.rb be true
  # Can have multiple values, must match all to be authorized
  required_groups:
    # If only a group name is given, membership will be checked against "uniqueMember"
    - cn=admins,ou=groups,dc=northwestern,dc=edu
    - cn=users,ou=groups,dc=northwestern,dc=edu
    # If an array is given, the first element will be the attribute to check against, the second the group name
    - ["moreMembers", "cn=users,ou=groups,dc=northwestern,dc=edu"]
  ## Requires config.ldap_check_attributes in devise.rb to be true
  ## Can have multiple attributes and values, must match all to be authorized
  require_attribute:
    objectClass: inetOrgPerson
    authorizationRole: postsAdmin

## Environment

development:
  host: registry.northwestern.edu
  port: 636
  attribute: uid
  base: ou=people,dc=northwestern,dc=edu
  admin_user: ENV['LDAP_USER']
  admin_password: ENV['LDAP_PASS']
  ssl: true

test:
  host: localhost
  port: 3389
  attribute: cn
  base: ou=people,dc=test,dc=com
  admin_user: cn=admin,dc=test,dc=com
  admin_password: admin_password
  ssl: simple_tls

development:
  host: registry.northwestern.edu
  port: 636
  attribute: uid
  base: ou=people,dc=northwestern,dc=edu
  admin_user: ENV['LDAP_USER']
  admin_password: ENV['LDAP_PASS']
  ssl: true

staging:
  host: registry.northwestern.edu
  port: 636
  attribute: uid
  base: ou=people,dc=northwestern,dc=edu
  admin_user: ENV['LDAP_USER']
  admin_password: ENV['LDAP_PASS']
  ssl: true
